export const TEMPLATE_CATEGORIES = [
  { id: "all", label: { id: "Semua", en: "All" } },
  { id: "kuliner", label: { id: "Kuliner", en: "Food" } },
  { id: "beauty", label: { id: "Beauty", en: "Beauty" } },
  { id: "retail", label: { id: "Retail", en: "Retail" } },
  { id: "jasa", label: { id: "Jasa", en: "Services" } },
  { id: "hospitality", label: { id: "Hospitality", en: "Hospitality" } },
  { id: "profesional", label: { id: "Profesional", en: "Professional" } },
];

const COMMON_FIELDS = [
  { key: "businessName", type: "text", group: "brand", label: { id: "Nama bisnis", en: "Business name" }, placeholder: { id: "Contoh: Kopi Pagi", en: "Example: Morning Coffee" }, required: true },
  { key: "logo", type: "image", group: "brand", label: { id: "Logo bisnis", en: "Business logo" } },
  { key: "primaryColor", type: "color", group: "brand", label: { id: "Warna utama", en: "Primary color" } },
  { key: "eyebrow", type: "text", group: "hero", label: { id: "Teks kecil di atas judul", en: "Text above the title" } },
  { key: "headline", type: "textarea", group: "hero", label: { id: "Judul utama", en: "Main headline" }, required: true },
  { key: "description", type: "textarea", group: "hero", label: { id: "Deskripsi singkat", en: "Short description" }, required: true },
  { key: "heroImage", type: "image", group: "hero", label: { id: "Foto utama", en: "Main photo" } },
  { key: "cta", type: "text", group: "hero", label: { id: "Tulisan tombol", en: "Button text" } },
  { key: "sectionTitle", type: "text", group: "content", label: { id: "Judul produk atau layanan", en: "Products or services title" } },
  { key: "item1Title", type: "text", group: "content", label: { id: "Produk atau layanan 1", en: "Product or service 1" } },
  { key: "item1Description", type: "textarea", group: "content", label: { id: "Deskripsi 1", en: "Description 1" } },
  { key: "item1Price", type: "text", group: "content", label: { id: "Harga 1", en: "Price 1" } },
  { key: "item2Title", type: "text", group: "content", label: { id: "Produk atau layanan 2", en: "Product or service 2" } },
  { key: "item2Description", type: "textarea", group: "content", label: { id: "Deskripsi 2", en: "Description 2" } },
  { key: "item2Price", type: "text", group: "content", label: { id: "Harga 2", en: "Price 2" } },
  { key: "item3Title", type: "text", group: "content", label: { id: "Produk atau layanan 3", en: "Product or service 3" } },
  { key: "item3Description", type: "textarea", group: "content", label: { id: "Deskripsi 3", en: "Description 3" } },
  { key: "item3Price", type: "text", group: "content", label: { id: "Harga 3", en: "Price 3" } },
  { key: "testimonial", type: "textarea", group: "content", label: { id: "Testimoni pelanggan", en: "Customer testimonial" } },
  { key: "whatsapp", type: "tel", group: "contact", label: { id: "Nomor WhatsApp", en: "WhatsApp number" }, placeholder: { id: "Contoh: 628123456789", en: "Example: 628123456789" }, required: true },
  { key: "instagram", type: "text", group: "contact", label: { id: "Instagram", en: "Instagram" } },
  { key: "address", type: "textarea", group: "contact", label: { id: "Alamat", en: "Address" } },
  { key: "mapsUrl", type: "url", group: "contact", label: { id: "Link Google Maps", en: "Google Maps link" } },
  { key: "hours", type: "text", group: "contact", label: { id: "Jam buka", en: "Opening hours" } },
];

const baseConfig = {
  logo: "",
  primaryColor: "#0d7c66",
  cta: "Pesan via WhatsApp",
  instagram: "@bisniskamu",
  mapsUrl: "https://maps.google.com",
  hours: "Senin - Sabtu, 08.00 - 20.00",
};

const EN_TEMPLATE_CONTENT = {
  "senja-coffee": {
    cta: "Order on WhatsApp", eyebrow: "Local coffee, personal stories",
    headline: "A place to return to for seriously good coffee.",
    description: "Selected beans from local farmers, brewed with care for slow mornings and long conversations.",
    sectionTitle: "Customer favorites",
    item1Title: "Senja Milk Coffee", item1Description: "Espresso, fresh milk, and palm sugar.", item1Price: "IDR 24,000",
    item2Title: "Manual Brew", item2Description: "A rotating selection of single-origin beans.", item2Price: "IDR 28,000",
    item3Title: "Butter Croissant", item3Description: "Baked fresh every morning, crisp on the outside.", item3Price: "IDR 22,000",
    testimonial: "The quality is consistent and the space always makes us want to return.", address: "24 Merdeka Street, Garut", hours: "Monday - Saturday, 8 AM - 8 PM",
  },
  "rasa-nusantara": {
    cta: "Order on WhatsApp", eyebrow: "Indonesian cuisine", headline: "Home-style flavors for every celebration.",
    description: "Fresh, halal, flexible catering packages for meetings, family events, and special days.", sectionTitle: "Selected packages",
    item1Title: "Meeting Package", item1Description: "Rice, main course, vegetables, and mineral water.", item1Price: "From IDR 35,000",
    item2Title: "Family Package", item2Description: "A complete menu for 6 to 8 people.", item2Price: "From IDR 325,000",
    item3Title: "Wedding Package", item3Description: "A complete menu with professional presentation.", item3Price: "Request a quote",
    testimonial: "On time, generous portions, and every guest loved it.", address: "Garut, West Java", hours: "Monday - Sunday, 7 AM - 7 PM",
  },
  "luma-beauty": {
    cta: "Book on WhatsApp", eyebrow: "A space for self-care", headline: "Treatments that bring your confidence back.",
    description: "Personalized treatments with curated products and experienced therapists.", sectionTitle: "Our treatments",
    item1Title: "Signature Facial", item1Description: "A 60-minute treatment tailored to your skin.", item1Price: "IDR 275,000",
    item2Title: "Hair Ritual", item2Description: "Scalp detox and restorative hair spa.", item2Price: "IDR 220,000",
    item3Title: "Nail Care", item3Description: "Neat manicure with premium color options.", item3Price: "IDR 150,000",
    testimonial: "The consultation was thorough and I felt the results after my first visit.", address: "8 Cimanuk Street, Garut", hours: "Monday - Sunday, 9 AM - 8 PM",
  },
  "ruang-lokal": {
    cta: "Shop on WhatsApp", eyebrow: "Made close, chosen well", headline: "Local collections for a life with more character.",
    description: "Discover selected pieces from Indonesian makers and order directly through WhatsApp.", sectionTitle: "New collection",
    item1Title: "Daily Tote", item1Description: "Heavy canvas with practical compartments.", item1Price: "IDR 189,000",
    item2Title: "Linen Shirt", item2Description: "A relaxed cut for long days.", item2Price: "IDR 249,000",
    item3Title: "Ceramic Cup", item3Description: "Handmade in limited quantities.", item3Price: "IDR 129,000",
    testimonial: "The products feel personal and ordering is incredibly easy.", address: "Online store, Indonesia", hours: "Monday - Saturday, 9 AM - 6 PM",
  },
  "gerak-rental": {
    cta: "Book on WhatsApp", eyebrow: "Easy journeys", headline: "Clean vehicles, clear pricing, ready to go.",
    description: "Daily rentals and out-of-town travel with professional drivers.", sectionTitle: "Choose your vehicle",
    item1Title: "City Car", item1Description: "Efficient and comfortable for city travel.", item1Price: "From IDR 350,000",
    item2Title: "Family MPV", item2Description: "Spacious for families and longer journeys.", item2Price: "From IDR 550,000",
    item3Title: "Premium Van", item3Description: "Extra room for small groups.", item3Price: "From IDR 900,000",
    testimonial: "The car arrived spotless and the team was responsive from the start.", address: "Garut and surrounding areas", hours: "Open daily, 24 hours",
  },
  "teduh-stay": {
    cta: "Check availability", eyebrow: "Pause for a while", headline: "Stay close to nature and leave with a lighter mind.",
    description: "A private villa with green views, local breakfast, and spaces designed for rest.", sectionTitle: "Ways to stay",
    item1Title: "Garden Room", item1Description: "A comfortable room with private garden access.", item1Price: "IDR 650,000/night",
    item2Title: "Family Cabin", item2Description: "Two bedrooms for a family getaway.", item2Price: "IDR 1,250,000/night",
    item3Title: "Whole Villa", item3Description: "Complete privacy for up to 10 guests.", item3Price: "IDR 2,400,000/night",
    testimonial: "Peaceful, spotless, and even more beautiful than the photos.", address: "Cipanas, Garut", hours: "Check-in 2 PM, check-out 12 PM",
  },
  "atlas-property": {
    cta: "Talk to an agent", eyebrow: "Selected property, sound decisions", headline: "Find the right space for your next move.",
    description: "Transparent advice and verified properties for living or investment.", sectionTitle: "Selected properties",
    item1Title: "Family Home", item1Description: "A calm neighborhood with easy city access.", item1Price: "From IDR 850 million",
    item2Title: "Strategic Shop House", item2Description: "A high-traffic location for a growing business.", item2Price: "From IDR 1.2 billion",
    item3Title: "Investment Land", item3Description: "Verified documents and strong growth potential.", item3Price: "Request details",
    testimonial: "The process was clear and we never felt pressured into a decision.", address: "Garut, West Java", hours: "Monday - Saturday, 9 AM - 5 PM",
  },
  "nalar-consulting": {
    cta: "Book a consultation", eyebrow: "Strategy you can act on", headline: "Helping businesses see problems more clearly.",
    description: "Strategy, operations, and growth guidance for business owners who want a more focused path forward.", sectionTitle: "How we help",
    item1Title: "Business Check-up", item1Description: "Problem mapping and a focused 90-day plan.", item1Price: "From IDR 2.5 million",
    item2Title: "Growth Sprint", item2Description: "Intensive guidance toward one business goal.", item2Price: "From IDR 6 million",
    item3Title: "Advisory Retainer", item3Description: "A monthly thinking partner for business owners.", item3Price: "Request a quote",
    testimonial: "The conversation was sharp, practical, and immediately changed how we work.", address: "Online consultations across Indonesia", hours: "Monday - Friday, 9 AM - 5 PM",
  },
};

export const TEMPLATE_LIBRARY = [
  {
    id: "senja-coffee",
    name: "Senja Coffee",
    category: "kuliner",
    categoryLabel: { id: "Kuliner", en: "Food" },
    description: { id: "Hangat, editorial, dan dibuat untuk kedai yang ingin mudah ditemukan.", en: "Warm, editorial, and made for cafes that want to be discovered." },
    price: 1369500,
    layout: "editorial",
    accent: "#9a4d2f",
    defaultConfig: {
      ...baseConfig,
      businessName: "Senja Coffee",
      primaryColor: "#9a4d2f",
      eyebrow: "Kopi lokal, cerita personal",
      headline: "Tempat pulang untuk kopi yang dibuat serius.",
      description: "Biji pilihan dari petani lokal, diracik perlahan untuk menemani pagi dan percakapan panjangmu.",
      heroImage: "/templates/marketplace-hero.png", heroImageGrid: true, heroImagePosition: "left top",
      sectionTitle: "Menu favorit",
      item1Title: "Kopi Susu Senja", item1Description: "Espresso, susu segar, dan gula aren.", item1Price: "Rp24.000",
      item2Title: "Manual Brew", item2Description: "Pilihan single origin yang berganti tiap pekan.", item2Price: "Rp28.000",
      item3Title: "Butter Croissant", item3Description: "Dipanggang setiap pagi, renyah di luar.", item3Price: "Rp22.000",
      testimonial: "Rasanya konsisten dan tempatnya selalu membuat ingin kembali.",
      whatsapp: "6281234567890", address: "Jl. Merdeka No. 24, Garut",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "rasa-nusantara",
    name: "Rasa Nusantara",
    category: "kuliner",
    categoryLabel: { id: "Kuliner", en: "Food" },
    description: { id: "Katalog menu yang berani untuk katering dan rumah makan lokal.", en: "A bold menu catalog for local caterers and restaurants." },
    price: 1469500,
    layout: "bold",
    accent: "#cf4a24",
    defaultConfig: {
      ...baseConfig,
      businessName: "Rasa Nusantara", primaryColor: "#cf4a24", eyebrow: "Masakan Indonesia",
      headline: "Rasa rumahan untuk setiap perayaan.", description: "Paket katering segar, halal, dan fleksibel untuk rapat, acara keluarga, hingga hari istimewa.",
      heroImage: "/templates/marketplace-services.png", heroImageGrid: true, heroImagePosition: "left top", sectionTitle: "Paket pilihan",
      item1Title: "Paket Rapat", item1Description: "Nasi, lauk utama, sayur, dan air mineral.", item1Price: "Mulai Rp35.000",
      item2Title: "Paket Keluarga", item2Description: "Pilihan menu untuk 6 sampai 8 orang.", item2Price: "Mulai Rp325.000",
      item3Title: "Paket Pernikahan", item3Description: "Menu lengkap dengan penyajian profesional.", item3Price: "Tanya penawaran",
      testimonial: "Tepat waktu, porsinya pas, dan semua tamu suka.", whatsapp: "6281234567890", address: "Garut, Jawa Barat",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "luma-beauty",
    name: "Luma Beauty",
    category: "beauty",
    categoryLabel: { id: "Beauty", en: "Beauty" },
    description: { id: "Tampilan lembut dan premium untuk salon, spa, serta klinik kecantikan.", en: "A soft premium look for salons, spas, and beauty clinics." },
    price: 1569500,
    layout: "soft",
    accent: "#9d5c70",
    defaultConfig: {
      ...baseConfig,
      businessName: "Luma Beauty", primaryColor: "#9d5c70", eyebrow: "Ruang untuk merawat diri",
      headline: "Perawatan yang membuatmu kembali percaya diri.", description: "Treatment personal dengan produk terkurasi dan terapis berpengalaman.",
      heroImage: "/templates/marketplace-hero.png", heroImageGrid: true, heroImagePosition: "right top", sectionTitle: "Perawatan kami",
      item1Title: "Signature Facial", item1Description: "Perawatan 60 menit sesuai kebutuhan kulit.", item1Price: "Rp275.000",
      item2Title: "Hair Ritual", item2Description: "Detoks kulit kepala dan hair spa.", item2Price: "Rp220.000",
      item3Title: "Nail Care", item3Description: "Manicure rapi dengan pilihan warna premium.", item3Price: "Rp150.000",
      testimonial: "Konsultasinya detail dan hasilnya terasa sejak kunjungan pertama.", whatsapp: "6281234567890", address: "Jl. Cimanuk No. 8, Garut",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "ruang-lokal",
    name: "Ruang Lokal",
    category: "retail",
    categoryLabel: { id: "Retail", en: "Retail" },
    description: { id: "Etalase modern untuk produk lokal, fashion, dan toko pilihan.", en: "A modern storefront for local products, fashion, and curated shops." },
    price: 1469500,
    layout: "catalog",
    accent: "#335c4c",
    defaultConfig: {
      ...baseConfig,
      businessName: "Ruang Lokal", primaryColor: "#335c4c", eyebrow: "Dibuat dekat, dipilih baik",
      headline: "Koleksi lokal untuk hidup yang lebih berkarakter.", description: "Temukan produk pilihan dari kreator Indonesia dan pesan langsung lewat WhatsApp.",
      heroImage: "/templates/marketplace-hero.png", heroImageGrid: true, heroImagePosition: "left bottom", sectionTitle: "Koleksi terbaru",
      item1Title: "Daily Tote", item1Description: "Kanvas tebal dengan kompartemen praktis.", item1Price: "Rp189.000",
      item2Title: "Linen Shirt", item2Description: "Potongan santai untuk hari yang panjang.", item2Price: "Rp249.000",
      item3Title: "Ceramic Cup", item3Description: "Dibuat tangan dalam jumlah terbatas.", item3Price: "Rp129.000",
      testimonial: "Produknya terasa personal dan proses pesannya sangat mudah.", whatsapp: "6281234567890", address: "Online store, Indonesia",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "gerak-rental",
    name: "Gerak Rental",
    category: "jasa",
    categoryLabel: { id: "Jasa", en: "Services" },
    description: { id: "Informasi armada dan pemesanan cepat untuk bisnis rental.", en: "Fleet information and quick booking for rental businesses." },
    price: 1569500,
    layout: "bold",
    accent: "#185da8",
    defaultConfig: {
      ...baseConfig,
      businessName: "Gerak Rental", primaryColor: "#185da8", eyebrow: "Perjalanan tanpa ribet",
      headline: "Armada bersih, harga jelas, siap berangkat.", description: "Sewa kendaraan harian dan perjalanan luar kota dengan pengemudi profesional.",
      heroImage: "/templates/marketplace-services.png", heroImageGrid: true, heroImagePosition: "right top", sectionTitle: "Pilihan armada",
      item1Title: "City Car", item1Description: "Irit dan nyaman untuk perjalanan dalam kota.", item1Price: "Mulai Rp350.000",
      item2Title: "Family MPV", item2Description: "Lega untuk keluarga dan perjalanan jauh.", item2Price: "Mulai Rp550.000",
      item3Title: "Premium Van", item3Description: "Ruang luas untuk rombongan kecil.", item3Price: "Mulai Rp900.000",
      testimonial: "Mobil datang bersih dan adminnya responsif dari awal.", whatsapp: "6281234567890", address: "Garut dan sekitarnya",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "teduh-stay",
    name: "Teduh Stay",
    category: "hospitality",
    categoryLabel: { id: "Hospitality", en: "Hospitality" },
    description: { id: "Halaman penuh suasana untuk vila, homestay, dan penginapan butik.", en: "An atmospheric page for villas, homestays, and boutique lodging." },
    price: 1769500,
    layout: "immersive",
    accent: "#476346",
    defaultConfig: {
      ...baseConfig,
      businessName: "Teduh Stay", primaryColor: "#476346", eyebrow: "Berhenti sejenak",
      headline: "Menginap dekat alam, pulang dengan pikiran ringan.", description: "Vila privat dengan pemandangan hijau, sarapan lokal, dan ruang yang dirancang untuk beristirahat.",
      heroImage: "/templates/marketplace-services.png", heroImageGrid: true, heroImagePosition: "left bottom", sectionTitle: "Pilihan menginap",
      item1Title: "Garden Room", item1Description: "Kamar nyaman dengan akses taman privat.", item1Price: "Rp650.000/malam",
      item2Title: "Family Cabin", item2Description: "Dua kamar untuk liburan keluarga.", item2Price: "Rp1.250.000/malam",
      item3Title: "Whole Villa", item3Description: "Privasi penuh hingga 10 tamu.", item3Price: "Rp2.400.000/malam",
      testimonial: "Suasananya tenang, bersih, dan lebih indah dari fotonya.", whatsapp: "6281234567890", address: "Cipanas, Garut",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "atlas-property",
    name: "Atlas Property",
    category: "profesional",
    categoryLabel: { id: "Profesional", en: "Professional" },
    description: { id: "Kredibel dan rapi untuk agen properti serta konsultan.", en: "Credible and polished for property agents and consultants." },
    price: 1869500,
    layout: "editorial",
    accent: "#234a74",
    defaultConfig: {
      ...baseConfig,
      businessName: "Atlas Property", primaryColor: "#234a74", eyebrow: "Properti pilihan, keputusan tepat",
      headline: "Temukan ruang yang cocok untuk langkah berikutnya.", description: "Konsultasi transparan dan pilihan properti terverifikasi untuk hunian maupun investasi.",
      heroImage: "/templates/marketplace-services.png", heroImageGrid: true, heroImagePosition: "right bottom", sectionTitle: "Properti pilihan",
      item1Title: "Rumah Keluarga", item1Description: "Lingkungan tenang dengan akses kota yang mudah.", item1Price: "Mulai Rp850 juta",
      item2Title: "Ruko Strategis", item2Description: "Lokasi ramai untuk bisnis yang bertumbuh.", item2Price: "Mulai Rp1,2 miliar",
      item3Title: "Tanah Investasi", item3Description: "Dokumen terverifikasi dan potensi berkembang.", item3Price: "Tanya detail",
      testimonial: "Prosesnya jelas dan kami tidak pernah merasa didorong mengambil keputusan.", whatsapp: "6281234567890", address: "Garut, Jawa Barat",
    },
    editableFields: COMMON_FIELDS,
  },
  {
    id: "nalar-consulting",
    name: "Nalar Consulting",
    category: "profesional",
    categoryLabel: { id: "Profesional", en: "Professional" },
    description: { id: "Minimal dan berwibawa untuk konsultan, legal, serta layanan B2B.", en: "Minimal and authoritative for consultants, legal, and B2B services." },
    price: 1769500,
    layout: "minimal",
    accent: "#162c48",
    defaultConfig: {
      ...baseConfig,
      businessName: "Nalar Consulting", primaryColor: "#162c48", eyebrow: "Strategi yang bisa dijalankan",
      headline: "Membantu bisnis melihat masalah dengan lebih jernih.", description: "Pendampingan strategi, operasi, dan pertumbuhan untuk pemilik usaha yang ingin bergerak lebih terarah.",
      heroImage: "/templates/marketplace-hero.png", heroImageGrid: true, heroImagePosition: "right bottom", sectionTitle: "Cara kami membantu",
      item1Title: "Business Check-up", item1Description: "Pemetaan masalah dan prioritas 90 hari.", item1Price: "Mulai Rp2,5 juta",
      item2Title: "Growth Sprint", item2Description: "Pendampingan intensif untuk satu target bisnis.", item2Price: "Mulai Rp6 juta",
      item3Title: "Advisory Retainer", item3Description: "Partner berpikir bulanan untuk pemilik usaha.", item3Price: "Tanya penawaran",
      testimonial: "Diskusinya tajam, praktis, dan langsung mengubah cara kami bekerja.", whatsapp: "6281234567890", address: "Konsultasi online seluruh Indonesia",
    },
    editableFields: COMMON_FIELDS,
  },
];

TEMPLATE_LIBRARY.forEach((template) => {
  template.defaultConfigEn = {
    ...template.defaultConfig,
    ...EN_TEMPLATE_CONTENT[template.id],
  };
});

export function getTemplateById(id) {
  return TEMPLATE_LIBRARY.find((template) => template.id === id);
}

export function formatTemplatePrice(price, lang = "id") {
  return new Intl.NumberFormat(lang === "id" ? "id-ID" : "en-US", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(price);
}

export const EDITOR_GROUPS = [
  { id: "brand", label: { id: "Identitas bisnis", en: "Business identity" } },
  { id: "hero", label: { id: "Bagian utama", en: "Main section" } },
  { id: "content", label: { id: "Produk dan layanan", en: "Products and services" } },
  { id: "contact", label: { id: "Kontak dan lokasi", en: "Contact and location" } },
];
